name: Build
on:
  push:
    branches:
      - dev
      - master

env:
  DOTNET_INSTALL_DIR: "./.dotnet"
  Solution_Name: try-github-actions.sln

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Build Solution
        run: dotnet build ${{ env.Solution_Name }}